# -*- coding: utf-8 -*-
"""IP

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13nPMrOWCAI2oPIQLs3t1AIVUalTO8CSr
"""

!pip install opencv-python

import cv2

from google.colab.patches import cv2_imshow
img = cv2.imread("/content/ronaldo.jpg")
cv2_imshow(img)

grayscale = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
cv2_imshow(grayscale)

cropped_image = img[80:280, 150:330]
cv2_imshow(cropped_image)

img1 = cv2.imread("/content/download.jpg")
cv2_imshow(img1)

print(f"The shape of image 1 and image 2 is {img.shape} and {img1.shape} respectively")

img1=cv2.resize(img1,(800,533))

print(f"The shape of image 1 and image 2 is {img.shape} and {img1.shape} respectively")

add = cv2.add(img,img1)
cv2_imshow(add)

sub=cv2.subtract(img,img1)
cv2_imshow(sub)

dest_and = cv2.bitwise_and(img, img1)
cv2_imshow(dest_and)

dest_or = cv2.bitwise_or(img, img1)
cv2_imshow(dest_or)

dest_xor = cv2.bitwise_xor(img1, img)
cv2_imshow(dest_xor)

dest_not = cv2.bitwise_not(img1)
cv2_imshow(dest_not)